export const ADD_LIST = 'ADD_LIST'
export const SET_LISTS = 'SET_LISTS'

export const ADD_LABEL = 'ADD_LABEL'
export const UPDATE_LABEL = 'UPDATE_LABEL'
export const DELETE_LABEL = 'DELETE_LABEL'
export const SET_LABELS = 'SET_LABELS'

export const ADD_CARD = 'ADD_CARD'
export const SET_CARDS = 'SET_CARDS'

export const SET_COLLABORATORS = 'SET_COLLABORATORS'

export const SET_LAST_ACTIVE_BOARD = 'SET_LAST_ACTIVE_BOARD'

export const SET_RETRIEVE_BOARD_LOADING = 'SET_RETRIEVE_BOARD_LOADING'
export const CLEAR_RETRIEVE_BOARD_LOADING = 'CLEAR_RETRIEVE_BOARD_LOADING'

export const SET_ADD_LIST_LOADING = 'SET_ADD_LIST_LOADING'
export const CLEAR_ADD_LIST_LOADING = 'CLEAR_ADD_LIST_LOADING'

export const SET_BOARD_ERROR = 'SET_BOARD_ERROR'
export const CLEAR_BOARD_ERROR = 'CLEAR_BOARD_ERROR'
