export const ADD_LIST = 'ADD_LIST'

export const SET_LISTS = 'SET_LISTS'

export const SET_GET_LISTS_LOADING = 'SET_GET_LISTS_LOADING'

export const CLEAR_GET_LISTS_LOADING = 'CLEAR_GET_LISTS_LOADING'

export const SET_ADD_LIST_LOADING = 'SET_ADD_LIST_LOADING'

export const CLEAR_ADD_LIST_LOADING = 'CLEAR_ADD_LIST_LOADING'

export const SET_BOARD_ERROR = 'SET_BOARD_ERROR'

export const CLEAR_BOARD_ERROR = 'CLEAR_BOARD_ERROR'
