export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'

export const CLEAR_AUTHENTICATED = 'CLEAR_AUTHENTICATED'

export const SET_AUTHENTICATING = 'SET_AUTHENTICATING'

export const CLEAR_AUTHENTICATING = 'CLEAR_AUTHENTICATING'

export const SET_ERROR = 'SET_AUTH_ERROR'

export const CLEAR_ERROR = 'CLEAR_AUTH_ERROR'