# Generated by Django 3.1.3 on 2021-01-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='cover_photo',
            new_name='image',
        ),
    ]
