# Generated by Django 3.1.3 on 2021-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210116_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.BinaryField(blank=True, editable=True),
        ),
    ]
