# Generated by Django 3.1.3 on 2021-01-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210117_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='order',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
