# Generated by Django 3.1.3 on 2021-03-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_card_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('id', 'order')},
        ),
    ]
