# Generated by Django 3.1.3 on 2021-01-26 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210126_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
