# Generated by Django 3.1.3 on 2021-03-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210304_1623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('board_list', 'order')},
        ),
    ]
