# Generated by Django 3.1.3 on 2021-01-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210126_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
