# Generated by Django 3.1.3 on 2021-02-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('title', 'board')},
        ),
    ]
