# Generated by Django 3.1.3 on 2021-02-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210207_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.board')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.card')),
            ],
            options={
                'verbose_name': 'Card',
            },
        ),
    ]
