# Generated by Django 3.1.3 on 2021-02-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210217_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label'},
        ),
        migrations.RemoveField(
            model_name='label',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(to='home.Label'),
        ),
    ]
