# Generated by Django 3.1.3 on 2021-02-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210218_2042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set(),
        ),
    ]
