# Generated by Django 3.1.3 on 2021-02-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210218_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='labels',
        ),
    ]
