# Generated by Django 3.1.3 on 2021-02-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_card_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='board_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(to='home.Label'),
        ),
    ]
