# Generated by Django 3.1.3 on 2021-02-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210225_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='labels',
        ),
    ]
