export const SET_BOARDS = 'SET_BOARDS'

export const ADD_BOARD = 'ADD_BOARD'

export const SET_ADD_BOARD_LOADING = 'SET_ADD_BOARD_LOADING'

export const CLEAR_ADD_BOARD_LOADING = 'CLEAR_ADD_BOARD_LOADING'

export const SET_GET_BOARDS_LOADING = 'SET_GET_BOARD_LOADING'

export const CLEAR_GET_BOARDS_LOADING = 'CLEAR_GET_BOARD_LOADING'

export const SET_HOME_ERROR = 'SET_HOME_ERROR'

export const CLEAR_HOME_ERROR = 'CLEAR_HOME_ERROR'