export const ADD_BOARDS = 'ADD_BOARDS'

export const ORDER_BOARDS = 'ORDER_BOARDS'

export const SET_ADD_BOARD_LOADING = 'SET_ADD_BOARD_LOADING'

export const CLEAR_ADD_BOARD_LOADING = 'CLEAR_ADD_BOARD_LOADING'

export const SET_GET_BOARDS_LOADING = 'SET_GET_BOARD_LOADING'

export const CLEAR_GET_BOARDS_LOADING = 'CLEAR_GET_BOARD_LOADING'

export const SET_ERROR = 'SET_HOME_ERROR'